import { defineDocs } from "@farming-labs/docs";
import { colorful } from "@farming-labs/theme/colorful";

export default defineDocs({
  entry: "docs",
  theme: colorful(),
  ordering: [
    {
      "slug": "quickstart"
    },
    {
      "slug": "installation"
    },
    {
      "slug": "api",
      "children": [
        {
          "slug": "cli",
          "children": [
            {
              "slug": "usage"
            }
          ]
        },
        {
          "slug": "exports"
        }
      ]
    },
    {
      "slug": "features",
      "children": [
        {
          "slug": "ai-responses"
        },
        {
          "slug": "developer-tools"
        }
      ]
    },
    {
      "slug": "architecture",
      "children": [
        {
          "slug": "overview"
        }
      ]
    },
    {
      "slug": "build",
      "children": [
        {
          "slug": "package-structure"
        }
      ]
    },
    {
      "slug": "cli",
      "children": [
        {
          "slug": "tooling"
        }
      ]
    },
    {
      "slug": "frontend",
      "children": [
        {
          "slug": "application"
        }
      ]
    }
  ],
  metadata: {
    titleTemplate: "%s – Docs",
    description: "Generated by @farming-labs/docs Cloud",
  },
});
